### ISSUE TITLE
ps1 how to not show  stremlink  console  window  ,because streamlinkw error can't run

### ISSUE THREAD

**Issue by 4bbu6j5885o3gpv6ss8** [bgh-github/streamlink-handoff#2]
at Desktop i may nircmd execmd streamlink  <url >  best

**Comment by bgh-github** [comment]
Hi there. I remember previously experimenting with `streamlinkw` but not having much success either.

The Streamlink [Twitch GUI] maintainer outlines much better than I could here that `streamlinkw` isn't intended to be run from command line - https://github.com/streamlink/streamlink/discussions/4324.

Agreed it would be preferable to not have the console displayed on Windows if it can be avoided though :)

With `nircmd execmd`, did you mean having it invoke `streamlink` properly suppresses the console window? If so, we can likely work it into a modified host PowerShell ps1 file.

**Comment by 4bbu6j5885o3gpv6ss8** [comment]
Thanks  Your answer     may  write  ps1  nircmd Script start method

**Comment by bgh-github** [comment]
Hi @4bbu6j5885o3gpv6ss8. Modifying the `Invoke-CimMethod` line of the host ps1 script as below should hopefully achieve what you're looking for

```powershell
Invoke-CimMethod -ClassName Win32_Process -Arguments @{CommandLine="$((Get-Command -Name nircmd).Source) execmd streamlink $Message"} -MethodName Create | Out-Null
```

Note: I couldn't get it to work using the absolute (typically %ProgramFiles%) Streamlink path for some reason. Possibly because of some WoW64 subtlety related to NirCmd being a 32-bit process. So for this to work it would be especially important Streamlink is in PATH

**Comment by 4bbu6j5885o3gpv6ss8** [comment]
very well It works perfectly! I also searched for a solution before  ,not solved.

**Comment by bgh-github** [comment]
Glad to hear it worked!

I didn't previously know about NirCmd, so it's been useful learning such an option is available.
