### ISSUE TITLE
Context menu is not visible

### ISSUE THREAD

**Issue by heubergen** [bgh-github/streamlink-handoff#4]
I simply can't see the context menu to begin with, neither on the Twitch Stream "test page" nor on Youtube.

I'm using macOS but the platform specific stuff should only occur later and shouldn't block the context menu, right?

**Comment by bgh-github** [comment]
Hello. Yes, the display of the context menu should be internal to the browser prior to native messaging parts.

A main thing to double check is the 'Run in Private Windows' option is allowed for the extension if running in that mode.

To confirm, you have the extension installed from the Mozilla add-ons site rather than building from the main branch? (Actions automation did recently perform a minor refresh to the URL list but I'm yet to fully test or prepare a new release)

**Comment by heubergen** [comment]
Yes, I'm using the AMO one (but also tried it with loading the latest version from the code but that didn't resolve the issue).

I also just tried it in a completely new profile with only this extensions installed and private windows enabled (even though I'm not in one) to no avail.

I'm using Firefox 115.2.1esr if that helps.

**Comment by bgh-github** [comment]
Good call on eliminating other extensions (as well as profile), that was going to be another suggestion.

I don't believe using ESR would be an issue, unless there was a system-level policy configured interfering in some way
https://support.mozilla.org/en-US/kb/enforcing-policies-firefox-enterprise

I just gave 115.2.1esr a quick try on Linux but unable to replicate the problem

It might be worth having a look through about:debugging > This Firefox > Inspect, or even general Developer Tools for anything jumping out.

Otherwise I'm a bit stumped. The context menu working usually doesn't have a lot of pitfalls.

**Comment by heubergen** [comment]
Looking at the code I finally understood what I had to do :) 

`contexts: ["link"]`

I was under the impression that I could just open the context menu on a yt page.

Sorry for the hassle.

**Comment by bgh-github** [comment]
No worries. I can see that being a source of confusion.

There was some reason I can't quite recall for enabling for links but not pages. Might revisit this as it may be possible to apply selectively to pages using the `documentUrlPatterns` parameter.

**Comment by bgh-github** [comment]
Hi @heubergen, quick mention that v2 of the extension just released will now also display the menu for matching URLs in document (page and tab) contexts.
